"""
Unified Import Script: Creates records in both DSpace and ArchivesSpace
Usage: python import_to_both.py <image_folder> [--prefix "Demo 1 - "]

This script:
1. Reads captions.csv (generated by caption_folder.py)
2. Creates/finds a DSpace Community and Collection
3. For each image:
   - Uploads to DSpace as an Item with Bitstream (publicly accessible)
   - Creates an ArchivesSpace Digital Object with embedded image from DSpace
"""

import argparse
import csv
import requests
import os
import sys
import time
import subprocess
import socket
from pathlib import Path
from urllib.parse import quote

# --- CONFIGURATION ---
# Load from config.py if it exists
try:
    from config import *
except ImportError:
    # Defaults if config.py not found
    DSPACE_API_URL = "http://localhost:8081/server/api"
    DSPACE_UI_URL = "http://localhost:4000"
    DSPACE_EMAIL = "your-email@example.com"
    DSPACE_PASSWORD = "your-password"
    DSPACE_COMMUNITY_NAME = "My Image Collection"
    DSPACE_COLLECTION_NAME = "2025 Images"
    AS_API_URL = "http://localhost:8089"
    AS_USERNAME = "admin"
    AS_PASSWORD = "admin"
    AS_REPO_ID = 2
    CSV_FILE = "captions.csv"
    LOCAL_IMAGE_SERVER = "http://localhost:8000"
    LOCAL_IMAGE_PORT = 8000


def is_port_in_use(port):
    """Check if a port is already in use."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('localhost', port)) == 0


def start_image_server(image_folder):
    """Start HTTP server to serve images for ArchivesSpace."""
    if is_port_in_use(LOCAL_IMAGE_PORT):
        print(f"[HTTP Server] Already running on port {LOCAL_IMAGE_PORT}")
        return None

    print(f"[HTTP Server] Starting on port {LOCAL_IMAGE_PORT}...")
    # Start server as background process
    process = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(LOCAL_IMAGE_PORT)],
        cwd=str(image_folder),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0
    )
    time.sleep(1)  # Give server time to start
    print(f"[HTTP Server] Running (PID: {process.pid})")
    return process


class DSpaceClient:
    """Handles DSpace 7/8 REST API interactions."""

    def __init__(self, base_url, email, password):
        self.base_url = base_url
        self.session = requests.Session()
        self.csrf_token = None
        self.auth_token = None
        self._authenticate(email, password)

    def _authenticate(self, email, password):
        """Authenticate and get CSRF + JWT tokens."""
        # First, hit the root API to get session cookies
        self.session.get(f"{self.base_url}")

        # Get CSRF token from cookies or header
        r = self.session.get(f"{self.base_url}/security/csrf")
        if r.status_code == 200:
            self.csrf_token = r.json().get("token")

        # Also check for DSPACE-XSRF-COOKIE
        if "DSPACE-XSRF-COOKIE" in self.session.cookies:
            self.csrf_token = self.session.cookies["DSPACE-XSRF-COOKIE"]

        # Login with proper headers
        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "X-XSRF-TOKEN": self.csrf_token
        }

        r = self.session.post(
            f"{self.base_url}/authn/login",
            data={"user": email, "password": password},
            headers=headers
        )

        if r.status_code == 200:
            self.auth_token = r.headers.get("Authorization")
            # Update CSRF after login
            if "DSPACE-XSRF-COOKIE" in self.session.cookies:
                self.csrf_token = self.session.cookies["DSPACE-XSRF-COOKIE"]
            print(f"[DSpace] Authenticated as {email}")
        else:
            raise Exception(f"[DSpace] Auth failed: {r.status_code} - {r.text}")

    def _headers(self, content_type="application/json"):
        """Build headers with auth and CSRF tokens."""
        h = {"Authorization": self.auth_token}
        if content_type:
            h["Content-Type"] = content_type
        if self.csrf_token:
            h["X-XSRF-TOKEN"] = self.csrf_token
        return h

    def _refresh_csrf(self):
        """Refresh CSRF token from cookies."""
        if "DSPACE-XSRF-COOKIE" in self.session.cookies:
            self.csrf_token = self.session.cookies["DSPACE-XSRF-COOKIE"]

    def get_or_create_community(self, name):
        """Find existing community or create new one."""
        # Search for existing
        r = self.session.get(
            f"{self.base_url}/core/communities",
            headers=self._headers()
        )
        if r.status_code == 200:
            communities = r.json().get("_embedded", {}).get("communities", [])
            for c in communities:
                if c.get("name") == name:
                    print(f"[DSpace] Found community: {c['uuid']}")
                    return c["uuid"]

        # Create new
        self._refresh_csrf()
        payload = {
            "name": name,
            "metadata": {
                "dc.title": [{"value": name}],
                "dc.description": [{"value": "Archival images from the Memphis Lantern Parade"}]
            }
        }
        r = self.session.post(
            f"{self.base_url}/core/communities",
            json=payload,
            headers=self._headers()
        )
        if r.status_code == 201:
            uuid = r.json()["uuid"]
            print(f"[DSpace] Created community: {uuid}")
            return uuid
        else:
            raise Exception(f"[DSpace] Failed to create community: {r.text}")

    def get_or_create_collection(self, community_uuid, name):
        """Find existing collection or create new one in community."""
        # Search for existing
        r = self.session.get(
            f"{self.base_url}/core/communities/{community_uuid}/collections",
            headers=self._headers()
        )
        if r.status_code == 200:
            collections = r.json().get("_embedded", {}).get("collections", [])
            for c in collections:
                if c.get("name") == name:
                    print(f"[DSpace] Found collection: {c['uuid']}")
                    return c["uuid"]

        # Create new - POST to /core/collections with parent community in query param
        self._refresh_csrf()
        payload = {
            "name": name,
            "metadata": {
                "dc.title": [{"value": name}],
                "dc.description": [{"value": "Images from the 2025 Memphis Lantern Parade"}]
            }
        }
        r = self.session.post(
            f"{self.base_url}/core/collections",
            json=payload,
            headers=self._headers(),
            params={"parent": community_uuid}
        )
        if r.status_code == 201:
            uuid = r.json()["uuid"]
            print(f"[DSpace] Created collection: {uuid}")
            return uuid
        else:
            raise Exception(f"[DSpace] Failed to create collection: {r.text}")

    def create_and_publish_item(self, collection_uuid, title, description, keywords, file_path, filename):
        """Create an Item directly via admin API and upload bitstream. Returns (item_uuid, bitstream_uuid)."""
        self._refresh_csrf()

        # Method: Create item directly via /core/items (admin approach)
        # This bypasses the submission workflow entirely

        # Build item metadata
        metadata = {
            "dc.title": [{"value": title, "language": None}],
            "dc.description.abstract": [{"value": description, "language": None}],
            "dc.type": [{"value": "Image", "language": None}]
        }

        # Add keywords as subjects
        for kw in keywords.split(";"):
            kw = kw.strip()
            if kw:
                if "dc.subject" not in metadata:
                    metadata["dc.subject"] = []
                metadata["dc.subject"].append({"value": kw, "language": None})

        # Create item directly
        item_payload = {
            "name": title,
            "metadata": metadata,
            "inArchive": True,
            "discoverable": True,
            "withdrawn": False
        }

        r = self.session.post(
            f"{self.base_url}/core/items",
            json=item_payload,
            headers=self._headers(),
            params={"owningCollection": collection_uuid}
        )

        if r.status_code not in [200, 201]:
            print(f"  [DSpace] Direct item creation failed: {r.status_code} - {r.text}")
            # Fall back to workspace approach
            return self._create_via_workspace(collection_uuid, title, description, keywords, file_path, filename)

        item = r.json()
        item_uuid = item.get("uuid")
        print(f"  [DSpace] Created item directly: {item_uuid}")

        # Upload bitstream to the item
        bitstream_uuid = self._upload_bitstream_to_item(item_uuid, file_path, filename)

        return item_uuid, bitstream_uuid

    def _upload_bitstream_to_item(self, item_uuid, file_path, filename):
        """Upload a bitstream to an existing item."""
        self._refresh_csrf()

        # First, get or create the ORIGINAL bundle
        r = self.session.get(
            f"{self.base_url}/core/items/{item_uuid}/bundles",
            headers=self._headers()
        )

        bundle_uuid = None
        if r.status_code == 200:
            bundles = r.json().get("_embedded", {}).get("bundles", [])
            for b in bundles:
                if b.get("name") == "ORIGINAL":
                    bundle_uuid = b["uuid"]
                    break

        # Create ORIGINAL bundle if it doesn't exist
        if not bundle_uuid:
            self._refresh_csrf()
            bundle_payload = {"name": "ORIGINAL", "metadata": {}}
            r = self.session.post(
                f"{self.base_url}/core/items/{item_uuid}/bundles",
                json=bundle_payload,
                headers=self._headers()
            )
            if r.status_code in [200, 201]:
                bundle_uuid = r.json().get("uuid")
                print(f"  [DSpace] Created ORIGINAL bundle: {bundle_uuid}")
            else:
                print(f"  [DSpace] Bundle creation failed: {r.status_code}")
                return None

        # Upload bitstream to bundle
        self._refresh_csrf()

        # Normalize extension to jpeg
        if filename.lower().endswith('.jpg'):
            upload_name = filename[:-4] + '.jpeg'
        else:
            upload_name = filename

        with open(file_path, "rb") as f:
            headers = {
                "Authorization": self.auth_token,
                "X-XSRF-TOKEN": self.csrf_token
            }

            files = {"file": (upload_name, f, "image/jpeg")}

            r = self.session.post(
                f"{self.base_url}/core/bundles/{bundle_uuid}/bitstreams",
                files=files,
                headers=headers
            )

            if r.status_code in [200, 201]:
                bitstream_uuid = r.json().get("uuid")
                print(f"  [DSpace] Uploaded bitstream: {bitstream_uuid}")
                return bitstream_uuid
            else:
                print(f"  [DSpace] Bitstream upload failed: {r.status_code} - {r.text}")
                return None

    def _create_via_workspace(self, collection_uuid, title, description, keywords, file_path, filename):
        """Fallback: Create item via workspace (may require approval)."""
        self._refresh_csrf()

        # Create workspace item
        r = self.session.post(
            f"{self.base_url}/submission/workspaceitems",
            headers=self._headers(),
            params={"owningCollection": collection_uuid}
        )
        if r.status_code != 201:
            raise Exception(f"[DSpace] Failed to create workspace item: {r.text}")

        workspace_item = r.json()
        workspace_id = workspace_item["id"]
        item_uuid = workspace_item.get("_embedded", {}).get("item", {}).get("uuid")

        print(f"  [DSpace] Created workspace item {workspace_id} (fallback mode)")

        # Upload bitstream
        self._refresh_csrf()
        bitstream_uuid = None

        if filename.lower().endswith('.jpg'):
            upload_name = filename[:-4] + '.jpeg'
        else:
            upload_name = filename

        with open(file_path, "rb") as f:
            files = {"file": (upload_name, f, "image/jpeg")}
            headers = {"Authorization": self.auth_token, "X-XSRF-TOKEN": self.csrf_token}

            r = self.session.post(
                f"{self.base_url}/submission/workspaceitems/{workspace_id}",
                files=files,
                headers=headers
            )

            if r.status_code in [200, 201]:
                resp_data = r.json() if r.text else {}
                files_list = resp_data.get("sections", {}).get("upload", {}).get("files", [])
                if files_list:
                    bitstream_uuid = files_list[0].get("uuid")
                print(f"  [DSpace] Uploaded file (workspace): {bitstream_uuid}")

        # Try to submit (may fail if workflow required)
        self._refresh_csrf()
        deposit_headers = self._headers("text/uri-list")
        workspace_uri = f"{self.base_url}/submission/workspaceitems/{workspace_id}"

        r = self.session.post(
            f"{self.base_url}/workflow/workflowitems",
            data=workspace_uri,
            headers=deposit_headers
        )

        if r.status_code in [200, 201]:
            print(f"  [DSpace] Item submitted to workflow")
        else:
            print(f"  [DSpace] Item in workspace (may need admin approval)")

        return item_uuid, bitstream_uuid

        # If bitstream_uuid not found, try to get it from the item
        if not bitstream_uuid and item_uuid:
            r = self.session.get(
                f"{self.base_url}/core/items/{item_uuid}/bundles",
                headers=self._headers()
            )
            if r.status_code == 200:
                bundles = r.json().get("_embedded", {}).get("bundles", [])
                for b in bundles:
                    if b.get("name") == "ORIGINAL":
                        # Get bitstreams in this bundle
                        bundle_uuid = b["uuid"]
                        r2 = self.session.get(
                            f"{self.base_url}/core/bundles/{bundle_uuid}/bitstreams",
                            headers=self._headers()
                        )
                        if r2.status_code == 200:
                            bitstreams = r2.json().get("_embedded", {}).get("bitstreams", [])
                            if bitstreams:
                                bitstream_uuid = bitstreams[0]["uuid"]
                        break

        return item_uuid, bitstream_uuid

    def add_archivesspace_link(self, item_uuid, aspace_uri, shared_id):
        """Add reverse link to ArchivesSpace and shared identifier."""
        if not item_uuid or not aspace_uri:
            return

        self._refresh_csrf()

        # Build the ArchivesSpace Staff UI URL from the API URI
        # aspace_uri is like /repositories/2/digital_objects/106
        # Use the resolve/readonly endpoint which handles repository context correctly
        aspace_staff_url = f"http://localhost/staff/resolve/readonly?uri={aspace_uri}"

        # Try adding fields one at a time to handle unregistered metadata fields
        # Use datacite.relation.isReferencedBy so link renders clickable on item page
        patch_fields = [
            ("/metadata/datacite.relation.isReferencedBy", [{"value": aspace_staff_url, "language": None}]),
            ("/metadata/dc.identifier.other", [{"value": shared_id, "language": None}]),
        ]

        success = False
        for field_path, field_value in patch_fields:
            self._refresh_csrf()
            patch_payload = [{"op": "add", "path": field_path, "value": field_value}]
            r = self.session.patch(
                f"{self.base_url}/core/items/{item_uuid}",
                json=patch_payload,
                headers=self._headers()
            )
            field_name = field_path.split("/")[-1]
            if r.status_code == 200:
                success = True
            else:
                print(f"  [DSpace] Note: {field_name} not available ({r.status_code})")

        if success:
            print(f"  [DSpace] Added ArchivesSpace link metadata")

    def get_item_handle(self, item_uuid):
        """Fetch the persistent Handle for a DSpace item."""
        r = self.session.get(
            f"{self.base_url}/core/items/{item_uuid}",
            headers=self._headers()
        )
        if r.status_code == 200:
            handle = r.json().get("handle")
            if handle:
                return handle
        return None

    def get_bitstream_url(self, bitstream_uuid):
        """Get the direct content URL for a bitstream."""
        if bitstream_uuid:
            return f"http://localhost:8081/server/api/core/bitstreams/{bitstream_uuid}/content"
        return None

    def get_item_url(self, item_uuid):
        """Get the public UI URL for an item."""
        return f"{DSPACE_UI_URL}/items/{item_uuid}"


class ArchivesSpaceClient:
    """Handles ArchivesSpace API interactions."""

    def __init__(self, base_url, username, password):
        self.base_url = base_url
        self.session = self._authenticate(username, password)

    def _authenticate(self, username, password):
        """Authenticate and get session token."""
        url = f"{self.base_url}/users/{username}/login?password={password}"
        r = requests.post(url)
        r.raise_for_status()
        token = r.json().get("session")
        print(f"[ArchivesSpace] Authenticated as {username}")
        return token

    def create_digital_object(self, repo_id, title, description, keywords, filename, image_url, dspace_page_url, shared_id, dspace_handle=None):
        """Create a Digital Object with embedded image, labeled DSpace link, and shared ID."""
        headers = {"X-ArchivesSpace-Session": self.session}

        # File versions: embedded image display
        file_versions = []

        # Primary: embedded image
        if image_url:
            file_versions.append({
                "jsonmodel_type": "file_version",
                "file_uri": image_url,
                "publish": True,
                "xlink_show_attribute": "embed",
                "xlink_actuate_attribute": "onLoad",
                "file_format_name": "jpeg",
                "use_statement": "image-thumbnail"
            })

        # DSpace link as file_version (clickable in UI)
        if dspace_page_url:
            file_versions.append({
                "jsonmodel_type": "file_version",
                "file_uri": dspace_page_url,
                "publish": True,
                "xlink_show_attribute": "new",
                "xlink_actuate_attribute": "onRequest"
            })

        # External documents: labeled link to DSpace
        external_documents = []
        if dspace_page_url:
            external_documents.append({
                "jsonmodel_type": "external_document",
                "title": "Link to DSpace Record",
                "location": dspace_page_url,
                "publish": True
            })

        # If we have a DSpace Handle, add it as an external document too
        if dspace_handle:
            external_documents.append({
                "jsonmodel_type": "external_document",
                "title": f"DSpace Persistent Handle ({dspace_handle})",
                "location": f"http://localhost:4000/handle/{dspace_handle}",
                "publish": True
            })

        # Build notes
        notes_content = description
        if dspace_handle:
            notes_content += f"\n\nDSpace Handle: {dspace_handle}"
        notes_content += f"\n\nKeywords: {keywords}"

        payload = {
            "jsonmodel_type": "digital_object",
            "title": title,
            "digital_object_id": shared_id,  # Shared identifier (same in DSpace dc.identifier.other)
            "publish": True,
            "file_versions": file_versions,
            "external_documents": external_documents,
            "notes": [
                {
                    "jsonmodel_type": "note_digital_object",
                    "type": "summary",
                    "content": [notes_content],
                    "publish": True
                }
            ]
        }

        url = f"{self.base_url}/repositories/{repo_id}/digital_objects"
        r = requests.post(url, headers=headers, json=payload, timeout=120)

        if r.status_code == 200:
            uri = r.json().get("uri")
            print(f"  [ArchivesSpace] Created Digital Object: {uri}")
            return uri
        else:
            print(f"  [ArchivesSpace] Failed: {r.text}")
            return None

    def create_collection_link(self, repo_id, collection_name, dspace_collection_url):
        """Create a Digital Object linking to the DSpace collection (collection-level link)."""
        headers = {"X-ArchivesSpace-Session": self.session}

        shared_id = f"dspace_collection_{int(time.time())}"

        payload = {
            "jsonmodel_type": "digital_object",
            "title": f"{collection_name} - DSpace Collection",
            "digital_object_id": shared_id,
            "publish": True,
            "file_versions": [{
                "jsonmodel_type": "file_version",
                "file_uri": dspace_collection_url,
                "publish": True,
                "xlink_show_attribute": "new",
                "xlink_actuate_attribute": "onRequest"
            }],
            "external_documents": [{
                "jsonmodel_type": "external_document",
                "title": "Link to DSpace Collection - View All Items",
                "location": dspace_collection_url,
                "publish": True
            }],
            "notes": [{
                "jsonmodel_type": "note_digital_object",
                "type": "summary",
                "content": [f"This record links to the full DSpace collection: {collection_name}. Click the link above to browse all items in DSpace."],
                "publish": True
            }]
        }

        url = f"{self.base_url}/repositories/{repo_id}/digital_objects"
        r = requests.post(url, headers=headers, json=payload, timeout=120)

        if r.status_code == 200:
            uri = r.json().get("uri")
            print(f"[ArchivesSpace] Created collection link: {uri}")
            return uri
        else:
            print(f"[ArchivesSpace] Collection link failed: {r.text}")
            return None


def main():
    parser = argparse.ArgumentParser(description="Import images to DSpace and ArchivesSpace")
    parser.add_argument("image_folder", help="Path to folder containing images")
    parser.add_argument("--prefix", "-p", default="", help="Prefix for titles (e.g., 'Demo 1 - ')")
    args = parser.parse_args()

    image_folder = Path(args.image_folder)
    prefix = args.prefix

    if not os.path.exists(CSV_FILE):
        print(f"Error: {CSV_FILE} not found. Run caption_folder.py first.")
        sys.exit(1)

    print("=" * 60)
    print("Unified Import: DSpace + ArchivesSpace")
    print("=" * 60)

    # Start HTTP server for ArchivesSpace images
    http_server = start_image_server(image_folder)

    # Initialize clients
    try:
        dspace = DSpaceClient(DSPACE_API_URL, DSPACE_EMAIL, DSPACE_PASSWORD)
        aspace = ArchivesSpaceClient(AS_API_URL, AS_USERNAME, AS_PASSWORD)
    except Exception as e:
        print(f"Authentication failed: {e}")
        sys.exit(1)

    # Setup DSpace structure (apply prefix to community/collection names)
    print("\n--- Setting up DSpace structure ---")
    community_name = f"{prefix}{DSPACE_COMMUNITY_NAME}" if prefix else DSPACE_COMMUNITY_NAME
    collection_name = f"{prefix}{DSPACE_COLLECTION_NAME}" if prefix else DSPACE_COLLECTION_NAME
    community_uuid = dspace.get_or_create_community(community_name)
    collection_uuid = dspace.get_or_create_collection(community_uuid, collection_name)

    # Create collection-level link in ArchivesSpace
    print("\n--- Creating collection-level link ---")
    dspace_collection_url = f"{DSPACE_UI_URL}/collections/{collection_uuid}"
    aspace.create_collection_link(AS_REPO_ID, collection_name, dspace_collection_url)

    # Process each image
    print("\n--- Processing images ---")
    results = []

    with open(CSV_FILE, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            filename = row['filename']
            title = f"{prefix}{row['title']}" if prefix else row['title']
            description = row['scope_content']
            keywords = row['keywords']

            file_path = image_folder / filename
            if not file_path.exists():
                print(f"Warning: {file_path} not found, skipping")
                continue

            print(f"\nProcessing: {filename}")

            # Generate shared identifier (used in both systems)
            shared_id = f"img_{int(time.time())}_{filename}"

            # 1. Create DSpace Item with bitstream
            item_uuid = None
            bitstream_uuid = None
            dspace_page_url = None
            dspace_handle = None

            try:
                item_uuid, bitstream_uuid = dspace.create_and_publish_item(
                    collection_uuid, title, description, keywords, str(file_path), filename
                )
                dspace_page_url = dspace.get_item_url(item_uuid) if item_uuid else None
                dspace_handle = dspace.get_item_handle(item_uuid) if item_uuid else None
                print(f"  DSpace item: {item_uuid}")
                if dspace_handle:
                    print(f"  DSpace Handle: {dspace_handle}")
            except Exception as e:
                print(f"  DSpace error: {e}")
                dspace_page_url = None

            # 2. Use LOCAL HTTP server URL for ArchivesSpace embedded image
            # URL-encode the filename to handle spaces and special characters
            local_image_url = f"{LOCAL_IMAGE_SERVER}/{quote(filename)}"
            print(f"  Image URL (local): {local_image_url}")

            # 3. Create ArchivesSpace Digital Object (with embedded image, labeled DSpace link, handle)
            as_uri = aspace.create_digital_object(
                AS_REPO_ID, title, description, keywords, filename,
                local_image_url, dspace_page_url, shared_id, dspace_handle
            )

            # 4. Add reverse link and shared ID: DSpace item → ArchivesSpace record
            if item_uuid and as_uri:
                dspace.add_archivesspace_link(item_uuid, as_uri, shared_id)

            results.append({
                "filename": filename,
                "dspace_item": item_uuid,
                "dspace_page": dspace_page_url,
                "local_image_url": local_image_url,
                "aspace_uri": as_uri
            })

            # Small delay between items
            time.sleep(0.5)

    # Summary
    print("\n" + "=" * 60)
    print("IMPORT COMPLETE")
    print("=" * 60)
    print(f"Records created: {len(results)}")
    print(f"\nDSpace Frontend: {DSPACE_UI_URL}")
    print(f"ArchivesSpace Staff: http://localhost/staff/")
    print("\nResults:")
    for r in results:
        print(f"  {r['filename']}")
        print(f"    DSpace Page:      {r['dspace_page']}")
        print(f"    Image (local):    {r['local_image_url']}")
        print(f"    ArchivesSpace:    {r['aspace_uri']}")

    print("\n" + "-" * 60)
    if http_server:
        print(f"NOTE: Python HTTP server started on port {LOCAL_IMAGE_PORT} (PID: {http_server.pid})")
        print("      This server will stop when you close the terminal or restart.")
    else:
        print(f"NOTE: Image server already running on port {LOCAL_IMAGE_PORT}")
        print("      (Docker image-server container or existing Python server)")
    print("      Images are served from: staging_images folder")
    print("-" * 60)


if __name__ == "__main__":
    main()
