"""
Unified Import Script: Creates records in DSpace, ArchivesSpace, AND VIVO
Usage: python import_to_trio.py <image_folder> [--prefix "Demo 1 - "]

This script extends import_to_both.py to include VIVO:
1. Reads captions.csv (generated by caption_folder.py)
2. Creates/finds a DSpace Community and Collection
3. For each image:
   - Uploads to DSpace as an Item with Bitstream (publicly accessible)
   - Creates an ArchivesSpace Digital Object with embedded image from DSpace
   - Creates a VIVO Dataset record with links to both systems
"""

import argparse
import csv
import requests
import os
import sys
import time
import subprocess
import socket
import uuid
from pathlib import Path
from urllib.parse import quote

# --- CONFIGURATION ---
# Load from config.py if it exists
try:
    from config import *
except ImportError:
    # Defaults if config.py not found
    DSPACE_API_URL = "http://localhost:8081/server/api"
    DSPACE_UI_URL = "http://localhost:4000"
    DSPACE_EMAIL = "your-email@example.com"
    DSPACE_PASSWORD = "your-password"
    DSPACE_COMMUNITY_NAME = "My Image Collection"
    DSPACE_COLLECTION_NAME = "2025 Images"
    AS_API_URL = "http://localhost:8089"
    AS_USERNAME = "admin"
    AS_PASSWORD = "admin"
    AS_REPO_ID = 2
    VIVO_URL = "http://localhost:8082"
    VIVO_EMAIL = "your-email@example.com"
    VIVO_PASSWORD = "your-password"
    VIVO_NAMESPACE = "http://vivo.mydomain.edu/individual/"
    VIVO_GRAPH = "http://vitro.mannlib.cornell.edu/default/vitro-kb-2"
    PHOTOGRAPHER_URI = "http://vivo.mydomain.edu/individual/photographer"
    PHOTOGRAPHER_NAME = "Photographer Name"
    PHOTOGRAPHER_FIRST = "First"
    PHOTOGRAPHER_LAST = "Last"
    PHOTOGRAPHER_EMAIL = "your-email@example.com"
    PHOTOGRAPHER_LOCATION = "City, State"
    PHOTOGRAPHER_WEBSITES = ["https://www.example.com"]
    CSV_FILE = "captions.csv"
    LOCAL_IMAGE_SERVER = "http://localhost:8000"
    LOCAL_IMAGE_PORT = 8000


def is_port_in_use(port):
    """Check if a port is already in use."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('localhost', port)) == 0


def start_image_server(image_folder):
    """Start HTTP server to serve images for ArchivesSpace."""
    if is_port_in_use(LOCAL_IMAGE_PORT):
        print(f"[HTTP Server] Already running on port {LOCAL_IMAGE_PORT}")
        return None

    print(f"[HTTP Server] Starting on port {LOCAL_IMAGE_PORT}...")
    process = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(LOCAL_IMAGE_PORT)],
        cwd=str(image_folder),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == "win32" else 0
    )
    time.sleep(1)
    print(f"[HTTP Server] Running (PID: {process.pid})")
    return process


class VIVOClient:
    """Handles VIVO SPARQL API interactions."""

    def __init__(self, base_url, email, password):
        self.base_url = base_url
        self.email = email
        self.password = password
        self.namespace = VIVO_NAMESPACE
        self.graph = VIVO_GRAPH
        self._test_connection()

    def _test_connection(self):
        """Test VIVO connection with a simple query."""
        query = "SELECT * WHERE { ?s ?p ?o } LIMIT 1"
        try:
            result = self.sparql_query(query)
            if "error" not in result.lower() and "403" not in result:
                print(f"[VIVO] Connected successfully (LOCAL instance)")
            else:
                raise Exception(f"VIVO connection test failed: {result[:200]}")
        except requests.RequestException as e:
            raise Exception(f"[VIVO] Connection failed: {e}")

    def get_or_create_photographer(self):
        """Get or create the photographer (Steve Eberhardt) in VIVO."""
        # Check if photographer already exists
        query = f"""
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?person WHERE {{
    <{PHOTOGRAPHER_URI}> a foaf:Person .
    BIND(<{PHOTOGRAPHER_URI}> AS ?person)
}}
"""
        result = self.sparql_query(query)
        if PHOTOGRAPHER_URI in result:
            print(f"[VIVO] Found photographer: {PHOTOGRAPHER_NAME}")
            return PHOTOGRAPHER_URI

        # Create photographer
        websites_triples = ""
        for i, url in enumerate(PHOTOGRAPHER_WEBSITES):
            websites_triples += f"""
        <{PHOTOGRAPHER_URI}> vivo:hasURL <{PHOTOGRAPHER_URI}-website-{i}> .
        <{PHOTOGRAPHER_URI}-website-{i}> a vivo:URLLink ;
            rdfs:label "{url.replace('https://www.', '')}" ;
            vivo:linkURI "{url}" ."""

        update = f"""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

INSERT DATA {{
    GRAPH <{self.graph}> {{
        <{PHOTOGRAPHER_URI}> a foaf:Person ;
            rdfs:label "{PHOTOGRAPHER_NAME}" ;
            obo:ARG_2000028 <{PHOTOGRAPHER_URI}-vcard> .
        <{PHOTOGRAPHER_URI}-vcard> a vcard:Individual ;
            vcard:hasName <{PHOTOGRAPHER_URI}-vcard-name> ;
            vcard:hasEmail <{PHOTOGRAPHER_URI}-vcard-email> ;
            vcard:hasAddress <{PHOTOGRAPHER_URI}-vcard-address> .
        <{PHOTOGRAPHER_URI}-vcard-name> a vcard:Name ;
            vcard:givenName "{PHOTOGRAPHER_FIRST}" ;
            vcard:familyName "{PHOTOGRAPHER_LAST}" .
        <{PHOTOGRAPHER_URI}-vcard-email> a vcard:Email ;
            vcard:email "{PHOTOGRAPHER_EMAIL}" .
        <{PHOTOGRAPHER_URI}-vcard-address> a vcard:Address ;
            vcard:locality "{PHOTOGRAPHER_LOCATION}" .
        {websites_triples}
    }}
}}
"""
        status, result = self.sparql_update(update)
        if status == 200:
            print(f"[VIVO] Created photographer: {PHOTOGRAPHER_NAME}")
            return PHOTOGRAPHER_URI
        else:
            print(f"[VIVO] Error creating photographer: {result[:200]}")
            return None

    def sparql_query(self, query):
        """Execute a SPARQL query against VIVO."""
        url = f"{self.base_url}/api/sparqlQuery"
        data = {
            "email": self.email,
            "password": self.password,
            "query": query
        }
        response = requests.post(url, data=data, timeout=30)
        return response.text

    def sparql_update(self, update):
        """Execute a SPARQL UPDATE against VIVO."""
        url = f"{self.base_url}/api/sparqlUpdate"
        data = {
            "email": self.email,
            "password": self.password,
            "update": update
        }
        response = requests.post(url, data=data, timeout=30)
        return response.status_code, response.text

    def create_dataset(self, title, description, dspace_url=None, archivesspace_url=None, keywords=None, photographer_uri=None, image_url=None):
        """Create a Dataset record in VIVO with links to other systems, photographer credit, and image."""
        uri = f"{self.namespace}dataset-{uuid.uuid4().hex[:8]}"

        # Escape special characters in strings
        title_escaped = title.replace('"', '\\"').replace('\n', ' ')
        desc_escaped = description.replace('"', '\\"').replace('\n', ' ') if description else ""

        # Build triples
        triples = f"""
        <{uri}> a <http://vivoweb.org/ontology/core#Dataset> ;
            rdfs:label "{title_escaped}" """

        # Add image using foaf:depiction and as a clickable link
        if image_url:
            triples += f""";
            <http://xmlns.com/foaf/0.1/depiction> <{image_url}> ;
            <http://vivoweb.org/ontology/core#hasURL> <{uri}-image-link> .
        <{uri}-image-link> a <http://vivoweb.org/ontology/core#URLLink> ;
            rdfs:label "View Photograph" ;
            <http://vivoweb.org/ontology/core#linkURI> "{image_url}" """

        if desc_escaped:
            triples += f""";
            <http://purl.org/ontology/bibo/abstract> "{desc_escaped}" """

        # Link to photographer via Authorship relationship
        if photographer_uri:
            authorship_uri = f"{uri}-authorship"
            triples += f""";
            <http://vivoweb.org/ontology/core#relatedBy> <{authorship_uri}> .
        <{authorship_uri}> a <http://vivoweb.org/ontology/core#Authorship> ;
            rdfs:label "Photographer: {PHOTOGRAPHER_NAME}" ;
            <http://vivoweb.org/ontology/core#relates> <{uri}> ;
            <http://vivoweb.org/ontology/core#relates> <{photographer_uri}> """

        # Add keywords as subjects
        if keywords:
            for kw in keywords.split(";"):
                kw = kw.strip().replace('"', '\\"')
                if kw:
                    triples += f""";
            <http://vivoweb.org/ontology/core#hasSubjectArea> "{kw}" """

        # Add DSpace link
        if dspace_url:
            triples += f""";
            <http://vivoweb.org/ontology/core#hasURL> <{uri}-dspace-link> .
        <{uri}-dspace-link> a <http://vivoweb.org/ontology/core#URLLink> ;
            rdfs:label "View in DSpace" ;
            <http://vivoweb.org/ontology/core#linkURI> "{dspace_url}" """

        # Add ArchivesSpace link
        if archivesspace_url:
            triples += f""";
            <http://vivoweb.org/ontology/core#hasURL> <{uri}-aspace-link> .
        <{uri}-aspace-link> a <http://vivoweb.org/ontology/core#URLLink> ;
            rdfs:label "View in ArchivesSpace" ;
            <http://vivoweb.org/ontology/core#linkURI> "{archivesspace_url}" """

        triples += " ."

        update = f"""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX bibo: <http://purl.org/ontology/bibo/>

INSERT DATA {{
    GRAPH <{self.graph}> {{
        {triples}
    }}
}}
"""
        status, result = self.sparql_update(update)
        if status == 200:
            return uri
        else:
            print(f"  [VIVO] Error creating dataset: {result[:200]}")
            return None

    def get_dataset_url(self, uri):
        """Get the public URL for a VIVO dataset."""
        # VIVO URIs are directly accessible
        return uri.replace(self.namespace, f"{self.base_url}/individual/")

    def upload_image(self, entity_uri, image_path):
        """Upload an image to a VIVO entity (appears in Photo placeholder)."""
        from PIL import Image

        # Get actual image dimensions for proper cropping
        try:
            img = Image.open(image_path)
            img_width, img_height = img.size
        except Exception:
            img_width, img_height = 800, 600  # Fallback

        # Calculate centered square crop (VIVO profile photos are square)
        crop_size = min(img_width, img_height)
        x_offset = (img_width - crop_size) // 2
        y_offset = (img_height - crop_size) // 2

        # Create a web session and login
        session = requests.Session()
        session.get(f"{self.base_url}/authenticate")
        session.post(f"{self.base_url}/authenticate",
                     data={"loginName": self.email, "loginPassword": self.password, "loginForm": "Log in"})

        # Step 1: Get the add page
        add_url = f"{self.base_url}/uploadImages?entityUri={quote(entity_uri)}&action=add"
        session.get(add_url)

        # Step 2: Upload the image
        upload_url = f"{self.base_url}/uploadImages?entityUri={quote(entity_uri)}&action=upload"
        with open(image_path, "rb") as f:
            filename = os.path.basename(image_path)
            r = session.post(upload_url, files={"datafile": (filename, f, "image/jpeg")})

        if r.status_code != 200:
            return False

        # Step 3: Submit crop form with centered square crop
        save_url = f"{self.base_url}/uploadImages?entityUri={quote(entity_uri)}&action=save"
        crop_data = {"x": str(x_offset), "y": str(y_offset), "w": str(crop_size), "h": str(crop_size)}
        r = session.post(save_url, data=crop_data)

        return r.status_code == 200


class DSpaceClient:
    """Handles DSpace 7/8 REST API interactions."""

    def __init__(self, base_url, email, password):
        self.base_url = base_url
        self.session = requests.Session()
        self.csrf_token = None
        self.auth_token = None
        self._authenticate(email, password)

    def _authenticate(self, email, password):
        """Authenticate and get CSRF + JWT tokens."""
        self.session.get(f"{self.base_url}")
        r = self.session.get(f"{self.base_url}/security/csrf")
        if r.status_code == 200:
            self.csrf_token = r.json().get("token")
        if "DSPACE-XSRF-COOKIE" in self.session.cookies:
            self.csrf_token = self.session.cookies["DSPACE-XSRF-COOKIE"]

        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "X-XSRF-TOKEN": self.csrf_token
        }
        r = self.session.post(
            f"{self.base_url}/authn/login",
            data={"user": email, "password": password},
            headers=headers
        )
        if r.status_code == 200:
            self.auth_token = r.headers.get("Authorization")
            if "DSPACE-XSRF-COOKIE" in self.session.cookies:
                self.csrf_token = self.session.cookies["DSPACE-XSRF-COOKIE"]
            print(f"[DSpace] Authenticated as {email}")
        else:
            raise Exception(f"[DSpace] Auth failed: {r.status_code} - {r.text}")

    def _headers(self, content_type="application/json"):
        h = {"Authorization": self.auth_token}
        if content_type:
            h["Content-Type"] = content_type
        if self.csrf_token:
            h["X-XSRF-TOKEN"] = self.csrf_token
        return h

    def _refresh_csrf(self):
        if "DSPACE-XSRF-COOKIE" in self.session.cookies:
            self.csrf_token = self.session.cookies["DSPACE-XSRF-COOKIE"]

    def get_or_create_community(self, name):
        r = self.session.get(f"{self.base_url}/core/communities", headers=self._headers())
        if r.status_code == 200:
            communities = r.json().get("_embedded", {}).get("communities", [])
            for c in communities:
                if c.get("name") == name:
                    print(f"[DSpace] Found community: {c['uuid']}")
                    return c["uuid"]

        self._refresh_csrf()
        payload = {
            "name": name,
            "metadata": {
                "dc.title": [{"value": name}],
                "dc.description": [{"value": "Archival images from the Memphis Lantern Parade"}]
            }
        }
        r = self.session.post(f"{self.base_url}/core/communities", json=payload, headers=self._headers())
        if r.status_code == 201:
            uuid = r.json()["uuid"]
            print(f"[DSpace] Created community: {uuid}")
            return uuid
        else:
            raise Exception(f"[DSpace] Failed to create community: {r.text}")

    def get_or_create_collection(self, community_uuid, name):
        r = self.session.get(
            f"{self.base_url}/core/communities/{community_uuid}/collections",
            headers=self._headers()
        )
        if r.status_code == 200:
            collections = r.json().get("_embedded", {}).get("collections", [])
            for c in collections:
                if c.get("name") == name:
                    print(f"[DSpace] Found collection: {c['uuid']}")
                    return c["uuid"]

        self._refresh_csrf()
        payload = {
            "name": name,
            "metadata": {
                "dc.title": [{"value": name}],
                "dc.description": [{"value": "Images from the 2025 Memphis Lantern Parade"}]
            }
        }
        r = self.session.post(
            f"{self.base_url}/core/collections",
            json=payload,
            headers=self._headers(),
            params={"parent": community_uuid}
        )
        if r.status_code == 201:
            uuid = r.json()["uuid"]
            print(f"[DSpace] Created collection: {uuid}")
            return uuid
        else:
            raise Exception(f"[DSpace] Failed to create collection: {r.text}")

    def create_and_publish_item(self, collection_uuid, title, description, keywords, file_path, filename):
        self._refresh_csrf()
        metadata = {
            "dc.title": [{"value": title, "language": None}],
            "dc.description.abstract": [{"value": description, "language": None}],
            "dc.type": [{"value": "Image", "language": None}],
            "dc.creator": [{"value": PHOTOGRAPHER_NAME, "language": None}],
            "dc.rights": [{"value": f"Photograph by {PHOTOGRAPHER_NAME}", "language": None}]
        }
        for kw in keywords.split(";"):
            kw = kw.strip()
            if kw:
                if "dc.subject" not in metadata:
                    metadata["dc.subject"] = []
                metadata["dc.subject"].append({"value": kw, "language": None})

        item_payload = {
            "name": title,
            "metadata": metadata,
            "inArchive": True,
            "discoverable": True,
            "withdrawn": False
        }

        r = self.session.post(
            f"{self.base_url}/core/items",
            json=item_payload,
            headers=self._headers(),
            params={"owningCollection": collection_uuid}
        )

        if r.status_code not in [200, 201]:
            print(f"  [DSpace] Direct item creation failed: {r.status_code}")
            return None, None

        item = r.json()
        item_uuid = item.get("uuid")
        print(f"  [DSpace] Created item: {item_uuid}")

        bitstream_uuid = self._upload_bitstream_to_item(item_uuid, file_path, filename)
        return item_uuid, bitstream_uuid

    def _upload_bitstream_to_item(self, item_uuid, file_path, filename):
        self._refresh_csrf()
        r = self.session.get(f"{self.base_url}/core/items/{item_uuid}/bundles", headers=self._headers())

        bundle_uuid = None
        if r.status_code == 200:
            bundles = r.json().get("_embedded", {}).get("bundles", [])
            for b in bundles:
                if b.get("name") == "ORIGINAL":
                    bundle_uuid = b["uuid"]
                    break

        if not bundle_uuid:
            self._refresh_csrf()
            bundle_payload = {"name": "ORIGINAL", "metadata": {}}
            r = self.session.post(
                f"{self.base_url}/core/items/{item_uuid}/bundles",
                json=bundle_payload,
                headers=self._headers()
            )
            if r.status_code in [200, 201]:
                bundle_uuid = r.json().get("uuid")

        self._refresh_csrf()
        if filename.lower().endswith('.jpg'):
            upload_name = filename[:-4] + '.jpeg'
        else:
            upload_name = filename

        with open(file_path, "rb") as f:
            headers = {"Authorization": self.auth_token, "X-XSRF-TOKEN": self.csrf_token}
            files = {"file": (upload_name, f, "image/jpeg")}
            r = self.session.post(
                f"{self.base_url}/core/bundles/{bundle_uuid}/bitstreams",
                files=files,
                headers=headers
            )
            if r.status_code in [200, 201]:
                bitstream_uuid = r.json().get("uuid")
                print(f"  [DSpace] Uploaded bitstream: {bitstream_uuid}")
                return bitstream_uuid
        return None

    def add_links(self, item_uuid, aspace_uri, vivo_uri, shared_id):
        """Add reverse links to ArchivesSpace and VIVO."""
        if not item_uuid:
            return

        self._refresh_csrf()
        aspace_staff_url = f"http://localhost/staff/resolve/readonly?uri={aspace_uri}" if aspace_uri else None
        vivo_url = vivo_uri.replace(VIVO_NAMESPACE, f"{VIVO_URL}/individual/") if vivo_uri else None

        patch_fields = []
        if aspace_staff_url:
            patch_fields.append(("/metadata/datacite.relation.isReferencedBy", [{"value": aspace_staff_url, "language": None}]))
        patch_fields.append(("/metadata/dc.identifier.other", [{"value": shared_id, "language": None}]))

        for field_path, field_value in patch_fields:
            self._refresh_csrf()
            patch_payload = [{"op": "add", "path": field_path, "value": field_value}]
            r = self.session.patch(
                f"{self.base_url}/core/items/{item_uuid}",
                json=patch_payload,
                headers=self._headers()
            )

        print(f"  [DSpace] Added cross-system links")

    def get_item_handle(self, item_uuid):
        r = self.session.get(f"{self.base_url}/core/items/{item_uuid}", headers=self._headers())
        if r.status_code == 200:
            return r.json().get("handle")
        return None

    def get_item_url(self, item_uuid):
        return f"{DSPACE_UI_URL}/items/{item_uuid}"


class ArchivesSpaceClient:
    """Handles ArchivesSpace API interactions."""

    def __init__(self, base_url, username, password):
        self.base_url = base_url
        self.session = self._authenticate(username, password)

    def _authenticate(self, username, password):
        url = f"{self.base_url}/users/{username}/login?password={password}"
        r = requests.post(url)
        r.raise_for_status()
        token = r.json().get("session")
        print(f"[ArchivesSpace] Authenticated as {username}")
        return token

    def create_digital_object(self, repo_id, title, description, keywords, filename, image_url,
                              dspace_page_url, shared_id, dspace_handle=None, vivo_url=None):
        """Create a Digital Object with links to all systems."""
        headers = {"X-ArchivesSpace-Session": self.session}

        file_versions = []
        if image_url:
            file_versions.append({
                "jsonmodel_type": "file_version",
                "file_uri": image_url,
                "publish": True,
                "xlink_show_attribute": "embed",
                "xlink_actuate_attribute": "onLoad",
                "file_format_name": "jpeg",
                "use_statement": "image-thumbnail"
            })
        if dspace_page_url:
            file_versions.append({
                "jsonmodel_type": "file_version",
                "file_uri": dspace_page_url,
                "publish": True,
                "xlink_show_attribute": "new",
                "xlink_actuate_attribute": "onRequest"
            })

        external_documents = []
        if dspace_page_url:
            external_documents.append({
                "jsonmodel_type": "external_document",
                "title": "Link to DSpace Record",
                "location": dspace_page_url,
                "publish": True
            })
        if dspace_handle:
            external_documents.append({
                "jsonmodel_type": "external_document",
                "title": f"DSpace Persistent Handle ({dspace_handle})",
                "location": f"http://localhost:4000/handle/{dspace_handle}",
                "publish": True
            })
        if vivo_url:
            external_documents.append({
                "jsonmodel_type": "external_document",
                "title": "Link to VIVO Research Record",
                "location": vivo_url,
                "publish": True
            })

        notes_content = description
        if dspace_handle:
            notes_content += f"\n\nDSpace Handle: {dspace_handle}"
        if vivo_url:
            notes_content += f"\n\nVIVO Record: {vivo_url}"
        notes_content += f"\n\nKeywords: {keywords}"

        payload = {
            "jsonmodel_type": "digital_object",
            "title": title,
            "digital_object_id": shared_id,
            "publish": True,
            "file_versions": file_versions,
            "external_documents": external_documents,
            "notes": [{
                "jsonmodel_type": "note_digital_object",
                "type": "summary",
                "content": [notes_content],
                "publish": True
            }]
        }

        url = f"{self.base_url}/repositories/{repo_id}/digital_objects"
        r = requests.post(url, headers=headers, json=payload, timeout=120)

        if r.status_code == 200:
            uri = r.json().get("uri")
            print(f"  [ArchivesSpace] Created Digital Object: {uri}")
            return uri
        else:
            print(f"  [ArchivesSpace] Failed: {r.text}")
            return None

    def create_collection_link(self, repo_id, collection_name, dspace_collection_url):
        headers = {"X-ArchivesSpace-Session": self.session}
        shared_id = f"dspace_collection_{int(time.time())}"

        payload = {
            "jsonmodel_type": "digital_object",
            "title": f"{collection_name} - DSpace Collection",
            "digital_object_id": shared_id,
            "publish": True,
            "file_versions": [{
                "jsonmodel_type": "file_version",
                "file_uri": dspace_collection_url,
                "publish": True,
                "xlink_show_attribute": "new",
                "xlink_actuate_attribute": "onRequest"
            }],
            "external_documents": [{
                "jsonmodel_type": "external_document",
                "title": "Link to DSpace Collection - View All Items",
                "location": dspace_collection_url,
                "publish": True
            }],
            "notes": [{
                "jsonmodel_type": "note_digital_object",
                "type": "summary",
                "content": [f"This record links to the full DSpace collection: {collection_name}."],
                "publish": True
            }]
        }

        url = f"{self.base_url}/repositories/{repo_id}/digital_objects"
        r = requests.post(url, headers=headers, json=payload, timeout=120)

        if r.status_code == 200:
            uri = r.json().get("uri")
            print(f"[ArchivesSpace] Created collection link: {uri}")
            return uri
        return None


def main():
    parser = argparse.ArgumentParser(description="Import images to DSpace, ArchivesSpace, and VIVO")
    parser.add_argument("image_folder", help="Path to folder containing images")
    parser.add_argument("--prefix", "-p", default="", help="Prefix for titles (e.g., 'Demo 1 - ')")
    args = parser.parse_args()

    image_folder = Path(args.image_folder)
    prefix = args.prefix

    if not os.path.exists(CSV_FILE):
        print(f"Error: {CSV_FILE} not found. Run caption_folder.py first.")
        sys.exit(1)

    print("=" * 60)
    print("TRIO Import: DSpace + ArchivesSpace + VIVO")
    print("=" * 60)

    http_server = start_image_server(image_folder)

    # Initialize all three clients
    try:
        dspace = DSpaceClient(DSPACE_API_URL, DSPACE_EMAIL, DSPACE_PASSWORD)
        aspace = ArchivesSpaceClient(AS_API_URL, AS_USERNAME, AS_PASSWORD)
        vivo = VIVOClient(VIVO_URL, VIVO_EMAIL, VIVO_PASSWORD)
    except Exception as e:
        print(f"Authentication failed: {e}")
        sys.exit(1)

    # Create/get photographer in VIVO
    print("\n--- Setting up VIVO photographer ---")
    photographer_uri = vivo.get_or_create_photographer()

    # Setup DSpace structure
    print("\n--- Setting up DSpace structure ---")
    community_name = f"{prefix}{DSPACE_COMMUNITY_NAME}" if prefix else DSPACE_COMMUNITY_NAME
    collection_name = f"{prefix}{DSPACE_COLLECTION_NAME}" if prefix else DSPACE_COLLECTION_NAME
    community_uuid = dspace.get_or_create_community(community_name)
    collection_uuid = dspace.get_or_create_collection(community_uuid, collection_name)

    # Create collection-level link in ArchivesSpace
    print("\n--- Creating collection-level link ---")
    dspace_collection_url = f"{DSPACE_UI_URL}/collections/{collection_uuid}"
    aspace.create_collection_link(AS_REPO_ID, collection_name, dspace_collection_url)

    # Process each image
    print("\n--- Processing images ---")
    results = []

    with open(CSV_FILE, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            filename = row['filename']
            title = f"{prefix}{row['title']}" if prefix else row['title']
            description = row['scope_content']
            keywords = row['keywords']

            file_path = image_folder / filename
            if not file_path.exists():
                print(f"Warning: {file_path} not found, skipping")
                continue

            print(f"\nProcessing: {filename}")

            shared_id = f"img_{int(time.time())}_{filename}"

            # 1. Create DSpace Item
            item_uuid, bitstream_uuid = None, None
            dspace_page_url, dspace_handle = None, None

            try:
                item_uuid, bitstream_uuid = dspace.create_and_publish_item(
                    collection_uuid, title, description, keywords, str(file_path), filename
                )
                dspace_page_url = dspace.get_item_url(item_uuid) if item_uuid else None
                dspace_handle = dspace.get_item_handle(item_uuid) if item_uuid else None
                if dspace_handle:
                    print(f"  DSpace Handle: {dspace_handle}")
            except Exception as e:
                print(f"  DSpace error: {e}")

            # 2. Build ArchivesSpace URL (we'll create the object next)
            local_image_url = f"{LOCAL_IMAGE_SERVER}/{quote(filename)}"

            # 3. Create VIVO Dataset (with links to DSpace and placeholder for ArchivesSpace)
            vivo_uri = None
            vivo_url = None
            try:
                vivo_uri = vivo.create_dataset(
                    title=title,
                    description=description,
                    dspace_url=dspace_page_url,
                    archivesspace_url=None,  # Will update after creating AS record
                    keywords=keywords,
                    photographer_uri=photographer_uri,
                    image_url=local_image_url
                )
                if vivo_uri:
                    vivo_url = vivo.get_dataset_url(vivo_uri)
                    print(f"  [VIVO] Created Dataset: {vivo_uri}")
                    # Upload image to VIVO (appears in Photo placeholder)
                    if vivo.upload_image(vivo_uri, str(file_path)):
                        print(f"  [VIVO] Uploaded photo")
            except Exception as e:
                print(f"  VIVO error: {e}")

            # 4. Create ArchivesSpace Digital Object (with links to DSpace AND VIVO)
            as_uri = aspace.create_digital_object(
                AS_REPO_ID, title, description, keywords, filename,
                local_image_url, dspace_page_url, shared_id, dspace_handle, vivo_url
            )

            # 5. Add reverse links to DSpace (ArchivesSpace + VIVO)
            if item_uuid:
                dspace.add_links(item_uuid, as_uri, vivo_uri, shared_id)

            # 6. Update VIVO with ArchivesSpace link (now that we have the URI)
            if vivo_uri and as_uri:
                aspace_staff_url = f"http://localhost/staff/resolve/readonly?uri={as_uri}"
                update = f"""
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

INSERT DATA {{
    GRAPH <{VIVO_GRAPH}> {{
        <{vivo_uri}> <http://vivoweb.org/ontology/core#hasURL> <{vivo_uri}-aspace-link> .
        <{vivo_uri}-aspace-link> a <http://vivoweb.org/ontology/core#URLLink> ;
            rdfs:label "View in ArchivesSpace" ;
            <http://vivoweb.org/ontology/core#linkURI> "{aspace_staff_url}" .
    }}
}}
"""
                vivo.sparql_update(update)

            results.append({
                "filename": filename,
                "dspace_item": item_uuid,
                "dspace_page": dspace_page_url,
                "aspace_uri": as_uri,
                "vivo_uri": vivo_uri,
                "vivo_url": vivo_url
            })

            time.sleep(0.5)

    # Summary
    print("\n" + "=" * 60)
    print("TRIO IMPORT COMPLETE")
    print("=" * 60)
    print(f"Records created: {len(results)}")
    print(f"\nSystem URLs:")
    print(f"  DSpace Frontend:    {DSPACE_UI_URL}")
    print(f"  ArchivesSpace:      http://localhost/staff/")
    print(f"  VIVO:               {VIVO_URL}")
    print("\nResults:")
    for r in results:
        print(f"  {r['filename']}")
        print(f"    DSpace:        {r['dspace_page']}")
        print(f"    ArchivesSpace: {r['aspace_uri']}")
        print(f"    VIVO:          {r['vivo_url']}")

    # Generate DSpace thumbnails
    print("\n--- Generating DSpace thumbnails ---")
    try:
        result = subprocess.run(
            ["docker", "exec", "dspace", "//dspace/bin/dspace", "filter-media"],
            capture_output=True,
            text=True,
            timeout=300
        )
        filtered_count = result.stdout.count("FILTERED:")
        print(f"[DSpace] Generated {filtered_count} thumbnail(s)")
    except Exception as e:
        print(f"[DSpace] Thumbnail generation error: {e}")

    print("\n" + "-" * 60)
    if http_server:
        print(f"NOTE: Image server running on port {LOCAL_IMAGE_PORT} (PID: {http_server.pid})")
    print("-" * 60)


if __name__ == "__main__":
    main()
